// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fsvghgwzagzmwjcyfczf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzdmdoZ3d6YWd6bXdqY3lmY3pmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMTcwMzYsImV4cCI6MjA2ODU5MzAzNn0.YrfeFmRAGBN2KTthunhdQvK2O8bxYbYlg1OXTH6IkVA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});